sudo: required
before_install:
  - sudo apt-get install -y postgresql-server-dev-all
  - sudo apt-get install -y libpcap-dev
  - sudo apt-get install -y libmagickwand-dev
  - sudo apt-get install -y imagemagick
  - sudo apt-get install -y tesseract-ocr
  - sudo apt-get install -y libsndfile1
  - sudo apt-get install -y libsndfile1-dev
language: ruby
rvm: # Rely upon .ruby-version
dist: trusty
after_success:
  - rubocop
